### ISSUE TITLE
config file /etc/rsyncd.conf not modified by upgrade from linbo2.x to linbo 4.x

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo7#86]
Hi Thomas,
upgrading from linbo 2.x to linbo 4.x changes the Imagefileformat and the extension.
In /etc/rsyncd.conf are exeptions for Fileextensions when rsync should not compress. *.qcow2 is missing in section linbo and section linbo-upload
Maybe we can replace the conffile in a future Update of linbo so "vintage" Installations might benefit as well :-)
yours
Holger

**Comment by dorianim** [comment]
This should be fixed in a more general and central approach, in my opinion. 
Otherwise, we will run into this kind of issue over and over again ...
Something like a `linuxmuster-upgrade` script, which base provides and calls all scripts in a hookdir where other packages can place their stuff (e.g. `/etc/linuxmuster/upgrade.d`).

Like this, a user could call `linuxmuster-upgrade` after every `apt upgrade` and rest assured, that everything is up-to-date.

**Comment by HappyBasher** [comment]
Will be fixed on the client side by rsync parameter `--skip-compression`. So it is irrelevant what in this regard is defined on the server.
